#!/usr/bin/env bash

set -xeuo pipefail

prefix=".brew-sync"

taps_file="${HOME}/${prefix}/taps"
packages_file="${HOME}/${prefix}/packages"

cmd="${1:-"up"}"

case $cmd in
  "init")
    mkdir "${HOME}/${prefix}"
    ;;
  "save")
    brew tap | sort -u > "${taps_file}"
    brew list | sort -u > "${packages_file}"
    ;;
  "up")
    brew update
    brew upgrade

    goal_taps=$(sort -u "${taps_file}")
    curr_taps=$(brew tap | sort -u)
    comm -23 <(printf '%s\n' "$goal_taps") <(printf '%s\n' "$curr_taps") |\
      xargs brew tap
    comm -13 <(printf '%s\n' "$goal_taps") <(printf '%s\n' "$curr_taps") |\
      xargs brew untap

    goal_packages=$(sort -u "${packages_file}")
    curr_packages=$(brew list | sort -u)
    comm -23 <(printf '%s\n' "$goal_packages") <(printf '%s\n' "$curr_packages") |\
      xargs brew install
    comm -13 <(printf '%s\n' "$goal_packages") <(printf '%s\n' "$curr_packages") |\
      xargs brew uninstall -f

    brew autoremove
    ;;
  *)
    echo "${cmd} not valid command"
    ;;
esac

