#!/usr/bin/env bash

set -euo pipefail

brew list |\
  fzf --query "${1:-""}" \
    --bind 'ctrl-s:reload-sync(brew search {q})' \
    --bind 'ctrl-u:execute(brew uninstall {})+reload-sync(brew list)' \
    --bind 'ctrl-i:execute(brew install {})+reload-sync(brew list)' \
    --bind '?:preview(brew info {})' \
