#!/usr/bin/env bash

set -euo pipefail

query="${1:-""}"

preview="docker inspect {1}"

label="c-r: reload, c-o: copy, c-f: logs"

docker ps |\
  fzf --header-lines=1 --query="${query}" \
    --border='bottom' --border-label="${label}" --border-label-pos=2 \
    --preview='docker inspect {1}' --preview-label='docker inspect' \
    --bind 'ctrl-r:reload(docker ps)' \
    --bind 'ctrl-d:preview-half-page-down' \
    --bind 'ctrl-u:preview-half-page-up' \
    --bind 'ctrl-l:execute(docker logs -f {1})' \
    --bind 'ctrl-o:execute-silent(echo -n {1} | pbcopy)'
