#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# helper to run a docker image
###############################################################################

image="$(docker images | fzc 1 2)"

docker run --rm -ti "${@:1}" "${image}"
