#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# helper to run bash inside a docker container
###############################################################################

docker-run --entrypoint=/bin/bash "${@:2}"
