#!/usr/bin/env bash

set -xeuo pipefail

###############################################################################
# execute a command inside a docker container
###############################################################################

id="$(docker ps | fzf --header-lines=1 | choose 0)"

docker exec -ti "${id}" "${@:1}"
