#!/usr/bin/env bash

set -euo pipefail

cd "${1:-.}" || exit 1

deps=$(fx package.json \
  'Object.keys(x.dependencies).concat(Object.keys(x.devDependencies)).concat("lodash-es").filter(name => !name.match(/@(zillow-)?types\//))' |\
   jq -rc '.[]')

for dep in ${deps}; do
  package=$(require-resolve "${dep}/package.json" 2>&1)
  echo "${dep} type=$(fx "${package}" '.type ?? "commonjs"')"
done