#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# use fzf to select from a list of items, printing and choosing the 0th column
###############################################################################

header_lines="${1:-1}"
col="${2:-0}"

fzf --multi --header-lines="${header_lines}" | choose "${col}"
