#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# use fzf to select from a list of items, printing and choosing the 0th column
###############################################################################

col="${1:-0}"
headers="${2:-1}"

fzf --multi --header-lines="${headers}" | choose "${col}"
