#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# helper script for previewing a file with highlighted line number in fzf,
# taking care to center the highlighted line in the preview window. Pretty slick!
#
# Source: https://github.com/sharkdp/bat/issues/388#issuecomment-652292548
###############################################################################

declare -r file=$1
declare -i -r line=$2
declare -i -r lines=$LINES

# subtract 3 for the header
declare -i center=$(( (lines - 3) / 2 ))

if [ $line -lt $center ]; then
    center=$line
fi

declare -i -r start=$(( line - center ))
declare -i -r end=$(( lines + start ))

exec bat --color always --highlight-line $line --line-range $start:$end --paging never "$file"
