#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# git ignore changes to a file
###############################################################################

git update-index --assume-unchanged "${@:1}"
