#!/usr/bin/env bash

set -euo pipefail

pod=$(kubectl get pods | fzf --header-lines=1 -q "${2:-""}" | choose 0)
port="${1:-$(gum input --prompt "port? ")}"
kubectl port-forward "pods/${pod}" "${port}:${port}"
