#!/usr/bin/env bash

set -euo pipefail

type="${1:-"pod"}"
query="${2:-""}"

preview="kubectl describe ${type} {1} | bat --language=yaml --decorations=never"

kubectl get "${type}" |\
  fzf --header-lines=1 --query="${query}" \
    --preview="${preview}" \
    --bind 'ctrl-d:preview-half-page-down' \
    --bind 'ctrl-o:execute-silent(echo -n {1} | pbcopy)' \
    --bind "ctrl-l:preview(kubectl logs ${type}/{1} --follow)" \
    --bind 'ctrl-u:preview-half-page-up' \
    --bind "esc:preview(${preview})"
