#!/usr/bin/env bash

set -euo pipefail

type="${1:-"pod"}"
query="${2:-""}"

preview="kubectl describe ${type} {1} --show-events | bat --language=yaml --decorations=never"

kubectl get "${type}" |\
  fzf --header-lines=1 --query="${query}" \
    --border='bottom' --border-label='c-o: copy, c-l: logs' --border-label-pos=2 \
    --preview="${preview}" --preview-label='kubectl describe' \
    --bind 'ctrl-d:preview-half-page-down' \
    --bind 'ctrl-o:execute-silent(echo -n {1} | pbcopy)' \
    --bind "ctrl-l:execute(kubectl logs ${type}/{1} --follow)" \
    --bind 'ctrl-u:preview-half-page-up'
