#!/usr/bin/env bash

set -euo pipefail

type="${1:-"pod"}"
query="${2:-""}"

preview="kubectl describe ${type} {1} --show-events | bat --language=yaml --decorations=never"

logs="$([[ "${type}" == "pod"* ]] && echo "execute(kubectl logs ${type}/{1} --follow)" || echo "ignore" )"

label="c-r: reload, c-y: copy"
if [[ "${type}" == "pod"* ]]; then
  label="${label}, c-l: logs "
fi

kubectl get "${type}" |\
  fzf --header-lines=1 --query="${query}" \
    --border='bottom' --border-label="${label}" --border-label-pos=2 \
    --preview="${preview}" --preview-label='kubectl describe' \
    --bind "ctrl-r:reload(kubectl get ${type})" \
    --bind 'ctrl-d:preview-half-page-down' \
    --bind 'ctrl-y:execute-silent(echo -n {1} | pbcopy)' \
    --bind "ctrl-l:${logs}" \
    --bind 'ctrl-u:preview-half-page-up'
