#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# use node.js to resolve a (relative) path to a absolute path
###############################################################################

node -e "console.log(require('path').resolve(__dirname, '${1}'))"
