#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# use node.js url pacakge to parse a URL, printing the result as JSON
###############################################################################

url="${1}"

node -e "console.log(JSON.stringify(require('url').parse(\"${url}\", true), null, 2))"
