#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# use node.js require.resolve to print the version of a package on disk
###############################################################################

jq .version $(require-resolve "${1}/package.json")
