#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# fzf + ripgrep, what could go wrong?
#
# Source: https://github.com/junegunn/fzf/blob/master/ADVANCED.md#ripgrep-integration
###############################################################################

RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"

fzf --ansi --disabled --query "${INITIAL_QUERY}" \
    --bind "start:reload:${RG_PREFIX} {q}" \
    --bind "change:reload:sleep 0.1; ${RG_PREFIX} {q} || true" \
    --delimiter : \
    --preview 'fzf-bat-preview {1} {2}' \
    --bind 'enter:become(vim {1} +{2})'
