#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# clear the znap cache, forcing commands etc. to be re-evaluated
###############################################################################

prefix="${HOME}/.cache/zsh-snap"
entry="$(ls "${prefix}" | fzf)"

ls "${prefix}/${entry}" |\
  fzf --multi |\
  xargs -I % rm "${prefix}/${entry}/%"
